### ISSUE TITLE
230130 스터디 진행 방향 설정

### ISSUE THREAD

**Issue by deslog** [HotCodeBreakers/CodingTest#1]
### 개인 실력 공유

- 브라운: 프로그래머스 lv2, 백준 실버1
- 윌: 프로그래머스 lv2, 백준 실버2
- 레이몬드: 풀어봐야 알것같아용
- 잭: 프로그래머스 lv2. 백준 실버2

### 스터디 숙제

- 이코테 책 순서대로 알고리즘 유형 정함
    - 알고리즘 유형은 한명이 몰빵해서 12개 정해서 공유
        - 1: 박성수 / 2: 전승훈 / 3: 이지수 / 4: 김상효 (돌아갑니다~ 깃허브니까 실명제)
- 일주일에 한 유형을 정하고 → 12문제 고정해서 풀기
- 어떤 툴을 사용할지
    - 백준과 프로그래머스 반반 나눠서 문제 설정

### 스터디 진행 방식

- 언어
    - 윌: 파이썬
    - 레이몬드, 잭, 브라운: 스위프트
- 스터디 날짜
    - `매주 목요일 오전 10시`
- 스터디 진행 방식
    - 약 3시간 생각쓰
    - 2시간 동안 2문제 라이브로 풀어보기
        - 공부한 유형의 문제 2문제 풀기
        - 2문제 → `leetcode` 에서 풀이 (당일에 두개 선정!)
    - 남은시간
        - 유형별 몰랐던 부분 질문하고 이야기나누기
        - 숙제(12문제) 중 모르는 부분 이야기 나누기

### 우리가 사용하는 공유 툴

- google drive
    - 엑셀 → 문제공유
- notion
- github
    - 폴더구조
        
        ```bash
        그리디 / 박성수 / boj_1023.swift
        그리디 / 박성수 / pro_가장큰 네모찾기.swift
        ```
        
### 스터디 시간
- 23년 2월 9일 목요일 오전10시

### 숙제
- 이코테 첫번재 유형 `그리디`
- 알고리즘별 문제 12개 [📁 google drive excel](https://docs.google.com/spreadsheets/d/1C6P2WJJ_jewpF8mxgF3EmZyLvxR0qGp7/edit#gid=682306809)
- 알고리즘 / 자료구조 기초 내용 공부 및 지식공유
  - 기초 공부 진행 후, 지식 공유의 시간을 가질 예정입니다. (본인 블로그, 노션 등 자유롭게 지식을 남기고 공유헤주세요)
 
### (참고) 개인 이슈

- 레이몬드: 2월 12일 ~ 18일 (과제는 진행, 스터디 불참)
- 윌: 2월 9일 (과제는 진행, 스터디불참)

**Comment by SH0123** [comment]
깔끔한 정리 덕분에 의욕 +10 입니다

**Comment by sunshiningsoo** [comment]
최고네요...
