### ISSUE TITLE
[Solve] 이코테 구현

### ISSUE THREAD

**Issue by deslog** [HotCodeBreakers/CodingTest#13]
## 🔥 풀이할 문제를 입력해주세요

- [x] [boj_1157_단어 공부](https://www.acmicpc.net/problem/1157)
- [x] [boj_10431_줄세우기](https://www.acmicpc.net/problem/10431)
- [ ] [boj_16926_배열 돌리기1](https://www.acmicpc.net/problem/16926)
- [x] [boj_14467_소가 길을 건너간 이유1](https://www.acmicpc.net/problem/14467)
- [x] [boj_ 244_스위치 켜고 끄기](https://www.acmicpc.net/problem/1244)
- [x] [boj_14719_빗물](https://www.acmicpc.net/problem/14719)
- [x]  [boj_1138_한 줄로 서기](https://www.acmicpc.net/problem/1138)
- [x] [boj_1913_달팽이](https://www.acmicpc.net/problem/1913)
- [ ] [boj_20207_달력](https://www.acmicpc.net/problem/20207)
- [x] [boj_20546_기적의 매매법](https://www.acmicpc.net/problem/20546)
- [x] [boj_20291_파일 정리](https://www.acmicpc.net/problem/20291)
- [ ] [boj_15686_치킨 배달](https://www.acmicpc.net/problem/15686)

## 🔥 참고 레퍼런스

- 관련 레퍼런스가 있을 시에 연결

**Comment by sunshiningsoo** [comment]
역시 빠르시군요.. 빌려가겠습니다..ㅎ
