### ISSUE TITLE
[Solve] 이코테 DFS+BFS

### ISSUE THREAD

**Issue by SeonJeon** [HotCodeBreakers/CodingTest#17]
## 🔥 풀이할 문제를 입력해주세요

- [x] [boj_1743_음식물 피하기](https://www.acmicpc.net/problem/1743)
- [x] [boj_2210_숫자판 점프](https://www.acmicpc.net/problem/2210)
- [x] [boj_3184_양](https://www.acmicpc.net/problem/3184)
- [x] [boj_1941_소문난 칠공주](https://www.acmicpc.net/problem/1941)
- [x] [boj_10026_적록색약](https://www.acmicpc.net/problem/10026)
- [x] [boj_4963_섬의 개수](https://www.acmicpc.net/problem/4963)
- [ ] [boj_3055_탈출](https://www.acmicpc.net/problem/3055)
- [x] [boj_14716_현수막](https://www.acmicpc.net/problem/14716)
- [x] LV.2 [pro_타겟 넘버](https://school.programmers.co.kr/learn/courses/30/lessons/43165)
- [x] LV.3 [pro_네트워크](https://school.programmers.co.kr/learn/courses/30/lessons/43162)
- [x] LV.3 [pro_단어 변환](https://school.programmers.co.kr/learn/courses/30/lessons/43163)
- [ ] LV.3 [pro_여행 경로](https://school.programmers.co.kr/learn/courses/30/lessons/43164)

## 🔥 참고 레퍼런스

- 관련 레퍼런스가 있을 시에 연결

**Comment by deslog** [comment]
3번째 문제 내 순서인데....... 스틸당했다 4번째는 제가 갑니다,,, 🫠

**Comment by sunshiningsoo** [comment]
빡시군요..
