### ISSUE TITLE
[Solve] 이코테 그리디

### ISSUE THREAD

**Issue by deslog** [HotCodeBreakers/CodingTest#2]
## 🔥 풀이할 문제를 입력해주세요

- [x] [boj_4796_캠핑](https://www.acmicpc.net/problem/4796)
- [x] [boj_1449_수리공 항승](https://www.acmicpc.net/problem/1449)
- [x] [boj_1931_회의실 배정](https://www.acmicpc.net/problem/1931)
- [x] [boj_10610_30](https://www.acmicpc.net/problem/10610)
- [x] [boj_1783_병든 나이트](https://www.acmicpc.net/problem/1783)
- [x] [boj_1541_잃어버린괄호](https://www.acmicpc.net/problem/1541)
- [x]  LV.1 [pro_체육복](https://school.programmers.co.kr/learn/courses/30/lessons/42862)
- [x] LV.2 [pro_조이스틱](https://school.programmers.co.kr/learn/courses/30/lessons/42860)
- [x] LV.2 [pro_큰 수만들기](https://school.programmers.co.kr/learn/courses/30/lessons/42883)
- [x] LV.2 [pro_구명보트](https://school.programmers.co.kr/learn/courses/30/lessons/42885)
- [x] LV.3 [pro_섬 연결하기](https://school.programmers.co.kr/learn/courses/30/lessons/42861)
- [x] LV.3 [pro_단속카메라](https://school.programmers.co.kr/learn/courses/30/lessons/42884)

## 🔥 참고 레퍼런스

- [풀이과정과 고민의 흔적을 남기는 🥔](https://didu-story.tistory.com/category/Algorithm)

**Comment by deslog** [comment]
< 다음 이슈 만드시는 분들 복사해서 쓰세요! >

**Comment by deslog** [comment]
저보다 나중에 이슈 만드시는 분들 문제 작성하기 귀찮으니까 복사해서 쓰셔도 됩니당!

**Comment by sunshiningsoo** [comment]
쌩유베리감사입니다😏

**Comment by SH0123** [comment]
최고입니다 😎

**Comment by deslog** [comment]
### LV.2 [pro_큰 수만들기](https://school.programmers.co.kr/learn/courses/30/lessons/42883)
- 테케10 시간초과를 극복하지 못함
- stack을 활용한 풀이 참고해서 풀었음 (https://rldd.tistory.com/159?category=963241)

**Comment by SH0123** [comment]
질문... 있어요...

```swift
  for i in 0..<nameArr.count {
        idx = i + 1
        while idx < nameArr.count, nameArr[idx] == "A" {
            idx += 1
        }
```

잘 못풀겠어서 조이스틱 문제 이것 저것 참고하다가 브라운 코드에서도 봤는데, 
idx >= nameArr.count가 되는 경우에 while문의 nameArr[idx]가 out of range 에러가 나야할 것 같은데 어떻게해서 에러가 나지 않는걸까요... help..
@deslog

**Comment by deslog** [comment]
> 앞의 조건 idx < nameArr.count가 만족했다는 상황 전제하에 nameArr[idx] == "A" 조건이 실행되는걸까요..?
> @SH0123 

네, 일단 모든 조건문은 순서대로 진행됩니다! 이것때문에 헷갈리셨을까요?
순서대로 진행되기 때문에 `while`문을 통과할때도 `idx`가 `nameArr.count`보다 작은지 확인합니다. 그리고 만족한다면 A와 같은지 살펴보는거죠!   그래서,,, `idx`가 `nameArr.coun`t보다 커지면 `while`문을 통과하지 않기 때문에 `index` 오류가 나지 않습니다...!

**Comment by SH0123** [comment]
> > 앞의 조건 idx < nameArr.count가 만족했다는 상황 전제하에 nameArr[idx] == "A" 조건이 실행되는걸까요..?
> > @SH0123
> 
> 네, 일단 모든 조건문은 순서대로 진행됩니다! 이것때문에 헷갈리셨을까요? 순서대로 진행되기 때문에 `while`문을 통과할때도 `idx`가 `nameArr.count`보다 작은지 확인합니다. 그리고 만족한다면 A와 같은지 살펴보는거죠! 그래서,,, `idx`가 `nameArr.count`보다 커지면 `while`문을 통과하지 않기 때문에 `index` 오류가 나지 않습니다...!

오옹 감사합니다 브라운 ㅎㅎ

**Comment by deslog** [comment]
### LV.3 [pro_섬 연결하기](https://school.programmers.co.kr/learn/courses/30/lessons/42861)
- 알고리즘 생각해내지 못함
- 오답노트 해야할듯?! 📝
- [참고 레퍼런스 - 크루스칼 알고리즘](https://fomaios.tistory.com/entry/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EC%84%AC-%EC%97%B0%EA%B2%B0%ED%95%98%EA%B8%B0-Swift)
