### ISSUE TITLE
[Solve] 이코테 정렬

### ISSUE THREAD

**Issue by deslog** [HotCodeBreakers/CodingTest#29]
## 🔥 풀이할 문제를 입력해주세요

- [x] (브론즈1) [boj_23881_알고리즘 수업-선택정렬 1](https://www.acmicpc.net/problem/23881)
- [ ] (브론즈2) [boj_2750_수 정렬하기](https://www.acmicpc.net/problem/2750) 이거 sort 쓰지 마시오 ^___^ ⚠️
- [x] (실버5) [boj_1181_단어 정렬](https://www.acmicpc.net/problem/1181)
- [ ] (실버5) [boj_11004_K번째 수](https://www.acmicpc.net/problem/11004)
- [ ] (실버5) [boj_11650_좌표 정렬하기](https://www.acmicpc.net/problem/11650)
- [ ] (실버4) [boj_10825_국영수](https://www.acmicpc.net/problem/10825)
- [ ] (실버3) [boj_18310_안테나](https://www.acmicpc.net/problem/18310)
- [ ] (골드5) [boj_23970_알고리즘 수업-버블정렬 3](https://www.acmicpc.net/problem/23970)
- [ ] (골드4) [boj_1715_카드정렬하기](https://www.acmicpc.net/problem/1715)
- [ ] (골드4) [boj_23883_알고리즘 수업-선택정렬 3](https://www.acmicpc.net/problem/23883)
- [ ] (LV.1, 카카오) [pro_실패율](https://school.programmers.co.kr/learn/courses/30/lessons/42889)
- [ ] (LV.2, 고득점kit) [pro_H-Index](https://school.programmers.co.kr/learn/courses/30/lessons/42747)
- [ ] ⭐️보너스 문제 (플래티넘5) [boj_1517_버블소트](https://www.acmicpc.net/problem/1517)

## 🔥 참고 레퍼런스

- 풀이과정과 고민의 과정은 [🥔감자블로그](https://didu-story.tistory.com/category/Algorithm)에 올립니다아 많관부
- 다른 참고 레퍼런스가 있을시 댓글로 달게유

**Comment by deslog** [comment]
플래티넘... 무섭지만 보너스로 넣어뒀습니다. 정렬의 기본(????????기본이 왜 플래티넘?)이라고 하더라구요???????
이번 목표는... sort메서드 쓰지 않고 정렬 모두 이해하기~ !~!

**Comment by SH0123** [comment]
하하하 좋네요 ... ㅎㅎ sort 쓰지 않기 ..!!
