### ISSUE TITLE
[Solve] 이코테 DP

### ISSUE THREAD

**Issue by SH0123** [HotCodeBreakers/CodingTest#43]
## 🔥 풀이할 문제를 입력해주세요

- [x] (브론즈 2) [boj_10870_피보나치수_5](https://www.acmicpc.net/problem/10870) (연습용 문제)
- [x] (실버 3) [boj_2579_계단오르기](https://www.acmicpc.net/problem/2579)
- [x] (실버 3) [boj_11726_2xn 타일링](https://www.acmicpc.net/problem/11726)
- [x] (실버 2) [boj_11055_가장 큰 증가하는 부분 수열](https://www.acmicpc.net/problem/11055)
- [x] (골드 5) [boj_2293_동전1](https://www.acmicpc.net/problem/2293)
- [x] (골드 5) [boj_12865_평범한 배낭](https://www.acmicpc.net/problem/12865)
- [x] (골드 3) [boj_1520_내리막길](https://www.acmicpc.net/problem/1520)
- [ ] (Lv.3, 고득점 Kit) [pro_N으로 표현](https://school.programmers.co.kr/learn/courses/30/lessons/42895)
- [ ] (Lv.4, 고득점 Kit) [pro_사칙연산](https://school.programmers.co.kr/learn/courses/30/lessons/1843)

## 🔥 참고 레퍼런스

- 관련 레퍼런스가 있을 시에 연결

**Comment by deslog** [comment]
good!!
