### ISSUE TITLE
[Solve] 이코테 구현

### ISSUE THREAD

**Issue by SH0123** [HotCodeBreakers/CodingTest#5]
## 🔥 풀이할 문제를 입력해주세요

- [x] [boj_1157_단어 공부](https://www.acmicpc.net/problem/1157)
- [x] [boj_10431_줄세우기](https://www.acmicpc.net/problem/10431)
- [x] [boj_16926_배열 돌리기1](https://www.acmicpc.net/problem/16926)
- [x] [boj_14467_소가 길을 건너간 이유1](https://www.acmicpc.net/problem/14467)
- [x] [boj_ 244_스위치 켜고 끄기](https://www.acmicpc.net/problem/1244)
- [x] [boj_14719_빗물](https://www.acmicpc.net/problem/14719)
- [x]  [boj_1138_한 줄로 서기](https://www.acmicpc.net/problem/1138)
- [x] [boj_1913_달팽이](https://www.acmicpc.net/problem/1913)
- [x] [boj_20207_달력](https://www.acmicpc.net/problem/20207)
- [x] [boj_20546_기적의 매매법](https://www.acmicpc.net/problem/20546)
- [x] [boj_20291_파일 정리](https://www.acmicpc.net/problem/20291)
- [x] [boj_15686_치킨 배달](https://www.acmicpc.net/problem/15686)

## 🔥 참고 레퍼런스

아래의 자료들 시간날 때 읽어보고 자료 정리해보기 -> unicode 변환 코드 작성시에 utf8이 훨씬 performance가 좋았어서 이유를 찾고싶음
[UTF-8 Swift](https://www.swift.org/blog/utf8-string/)

**Comment by sunshiningsoo** [comment]
오이오이.. 천천히 하시라구...🤨

**Comment by SH0123** [comment]
> 오이오이.. 천천히 하시라구...🤨

ㅋㅋㅋㅋㅋ 내일부터 담주 토욜까지 일본에서 코딩을 안하기 위해서...

**Comment by SH0123** [comment]
15686 조합으로 풀었는데, 조합이 아닌 풀이 찾아보기 (여행 끝나고)
